name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: |
          yarn && yarn lint && yarn test && cd reader-sdk-react-native-quickstart && yarn
          yarn lint && cd ..
  # build-ios:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 14.x
  #         SQUARE_READER_SDK_APPLICATION_ID: ${{secrets.SQUARE_READER_SDK_APPLICATION_ID}}
  #         SQUARE_READER_SDK_REPOSITORY_PASSWORD: ${{secrets.SQUARE_READER_SDK_REPOSITORY_PASSWORD}}
  #       env:
  #         SQUARE_READER_SDK_APPLICATION_ID: ${{secrets.SQUARE_READER_SDK_APPLICATION_ID}}
  #         SQUARE_READER_SDK_REPOSITORY_PASSWORD: ${{secrets.SQUARE_READER_SDK_REPOSITORY_PASSWORD}}
  #     - run: |
  #         sudo arch -x86_64 gem install ffi
  #         cd reader-sdk-react-native-quickstart
  #         yarn
  #         cd ios && arch -x86_64 pod install
  #         ruby <(curl https://connect.squareup.com/readersdk-installer) install --app-id ${{ secrets.SQUARE_READER_SDK_APPLICATION_ID }} --repo-password ${{ secrets.SQUARE_READER_SDK_REPOSITORY_PASSWORD }}
  #     - name: Build iOS (debug)
  #       run: "xcodebuild \
  #         -workspace reader-sdk-react-native-quickstart/ios/RNReaderSDKSample.xcworkspace \
  #         -scheme RNReaderSDKSample \
  #         clean archive \
  #         -sdk iphoneos \
  #         -configuration Debug \
  #         -UseModernBuildSystem=NO \
  #         -archivePath $PWD/RNReaderSDKSample \
  #         CODE_SIGNING_ALLOWED=NO"
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Install npm dependencies
        uses: actions/checkout@v3
        with:
          SQUARE_READER_SDK_APPLICATION_ID: ${{secrets.SQUARE_SDK_APPLICATION_ID}}
          SQUARE_READER_SDK_REPOSITORY_PASSWORD: ${{secrets.SQUARE_SDK_REPOSITORY_PASSWORD}}
        env:
          SQUARE_READER_SDK_APPLICATION_ID: ${{secrets.SQUARE_SDK_APPLICATION_ID}}
          SQUARE_READER_SDK_REPOSITORY_PASSWORD: ${{secrets.SQUARE_SDK_REPOSITORY_PASSWORD}}
      - run: |
          cd reader-sdk-react-native-quickstart && yarn
          cd android
          ./gradlew clean build -PSQUARE_READER_SDK_APPLICATION_ID $SQUARE_READER_SDK_APPLICATION_ID -PSQUARE_READER_SDK_REPOSITORY_PASSWORD $SQUARE_READER_SDK_REPOSITORY_PASSWORD
